using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdvertiseServiceDataAccess
{
    public class SQLStorage
    {
        public static string searchQuery = "";
                
        public string Q_GET_ADVERTISEMENT_ID = "SELECT ADVERT_ID FROM  ADVERT_ADVERTISEMENT_DETAIL WHERE ADVERT_CODE=@refCode";

        public string Q_USER_AUTHENTICATION = "SELECT * FROM ADVERT_USER_ACCOUNT WHERE ADVERTISEME_NAME=@userName AND PASSWORD=@passWord";

        public string Q_GET_USER_PROFILE_DETAIL = "SELECT UP.*,'http://192.168.69.1/AdvertiseService'+RU.URL_STRING AS URL_STRING,UA.ADVERTISEME_NAME,UA.PASSWORD FROM ADVERT_USER_PROFILE UP LEFT JOIN ADVERT_RESORUCE_URL RU ON UP.PROFILE_IMAGE_URL=RU.URL_ID LEFT JOIN ADVERT_USER_ACCOUNT UA ON UP.USER_ID=UA.USER_ID WHERE UP.USER_ID=@userID";

        public string Q_IS_USERNAME_EXISTS = "SELECT * FROM ADVERT_USER_ACCOUNT WHERE ADVERTISEME_NAME=@userName";

        public string Q_GET_NEWUSER_USERID = " SELECT COALESCE( MAX(USER_ID),'0000') FROM ADVERT_USER_ACCOUNT";

        public string Q_CREATE_NEW_USER_ACCOUNT = "INSERT INTO ADVERT_USER_ACCOUNT (USER_ID,ADVERTISEME_NAME,PASSWORD,RECOVERY_EMAIL, SECURITY_QUESTION, ANSWER,REGISTERED_DATE) VALUES (@userID,@advertisemeName,@passWord,'','','',GETDATE())";

        public string Q_CREATE_NEW_USER_PROFILE = @"INSERT INTO ADVERT_USER_PROFILE(USER_ID, FULL_NAME, STATUS_MESSAGE, EMAIL, ADDRESS, CITY, COUNTRY, STATE, LANGUAGE, MOBILE_PHONE, HOME_PHONE, OFFICE_PHONE, HOME_PAGE, SOCIAL_FACEBOOK, SOCIAL_GOOGLE, SOCIAL_TWITTER, SOCIAL_SKYPE, PROFILE_IMAGE_URL)
                                                    VALUES( @userID,@fullName,@statusMsg,@email,@address,@city,@country,@state,@language,@mobilePhone,@homePhone,@OfficePhone,@homePage,@socialFB,@socialGP,@socialTW,@socialSK,@imageURL); ";


        public string Q_SAVE_PROFILE_IMAGE_URL = "INSERT INTO ADVERT_RESORUCE_URL VALUES(@userID,'profile image',@url);";

        public string Q_GET_ADVERT_SEARCH_RESULT = @"SELECT DISTINCT ADVERT.ADVERT_ID,ADVERT_TITLE,SELLER_NAME,SELL_PRICE,AVG(REVIEW_RATING) AS ADVERT_RATING,COUNT(REVIEW.ADVERT_ID) AS REVIEW_COUNT,'http://192.168.69.1/AdvertiseService'+URL_STRING AS RESOURCE_URL
                                                    FROM ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_ITEM_PRICE PRICE,ADVERT_USER_REVIEW REVIEW,ADVERT_PREVIEW_URL URL,ADVERT_SELLER_DETAIL SELLER
                                                    WHERE REVIEW.ADVERT_ID= ADVERT.ADVERT_ID AND URL_ID='ad'+REVIEW.ADVERT_ID AND SELLER.SELLER_ID=ADVERT.SELLER_ID AND ADVERT.ADVERT_ID=PRICE.ADVERT_ID
                                                    GROUP BY ADVERT.ADVERT_ID,ADVERT_TITLE,URL_STRING,SELL_PRICE,SELLER_NAME";

        public string Q_GET_ADVERT_DETAIL = @" SELECT ADVERT.ADVERT_ID, ADVERT.SELLER_ID, ADVERT_TITLE, ADVERT.USER_ID, PRODUCT_FEATURES, PRODUCT_DESCRIPTION, PRODUCT_DETAIL, ADDITIONAL_INFO, PRODUCT_NOTE, SELLER_OFFER_FLG,  ADVERT_URL, BUYONLINE_FLG, BUYONLINE_URL, 
                                            LIST_PRICE,SELL_PRICE, SAVE_AMOUNT, STAFF_PICK_FLG, SAVE_PERCENTAGE,SELLER_NAME,'http://192.168.69.1/AdvertiseService'+PREVIEW.URL_STRING
                                            FROM ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_ITEM_PRICE PRICE,ADVERT_SELLER_DETAIL SELLER,ADVERT_PREVIEW_URL PREVIEW
                                            WHERE ADVERT.ADVERT_ID=@advertID AND SELLER.SELLER_ID=ADVERT.SELLER_ID AND ADVERT.ADVERT_ID=PRICE.ADVERT_ID 
                                            AND PREVIEW.URL_ID='ad'+@advertID";

        public string Q_GET_ADVERT_RATING = @"SELECT AVG(REVIEW_RATING) AS ADVERT_RATING,COUNT(REVIEW.ADVERT_ID) AS REVIEW_COUNT,
                                            (SELECT COUNT(ADVERT_ID)  FROM ADVERT_USER_REVIEW WHERE REVIEW_RATING=5 AND ADVERT_ID=@advertID) AS RATE5_COUNT,
                                            (SELECT COUNT(ADVERT_ID)  FROM ADVERT_USER_REVIEW WHERE REVIEW_RATING= 4 AND ADVERT_ID=@advertID) AS RATE4_COUNT,
                                            (SELECT COUNT(ADVERT_ID)  FROM ADVERT_USER_REVIEW WHERE REVIEW_RATING= 3 AND ADVERT_ID=@advertID) AS RATE3_COUNT,
                                            (SELECT COUNT(ADVERT_ID)  FROM ADVERT_USER_REVIEW WHERE REVIEW_RATING= 2 AND ADVERT_ID=@advertID) AS RATE2_COUNT,
                                            (SELECT COUNT(ADVERT_ID)  FROM ADVERT_USER_REVIEW WHERE REVIEW_RATING= 1 AND ADVERT_ID=@advertID) AS RATE1_COUNT
                                            FROM ADVERT_USER_REVIEW REVIEW
                                            WHERE ADVERT_ID=@advertID";

        public string Q_GET_SELLER_DETAIL = @"SELECT DISTINCT SELLER_NAME,SELLER.USER_ID,
                                              (SELECT COUNT (REVIEW_ID) FROM ADVERT_SELLER_FEEDBACK WHERE SELLER_ID=@sellerID) AS REVIEW_COUNT,
                                              (SELECT COUNT (REVIEW_ID)  FROM ADVERT_SELLER_FEEDBACK WHERE SELLER_ID=@sellerID AND REVIEW_FLG=1) AS POSITIVE_COUNT,
                                              SUM(REVIEW_FLG) AS SELLER_RATING,REGISTERED_DATE,'http://192.168.69.1/AdvertiseService'+RESOURCE.URL_STRING
                                              FROM ADVERT_SELLER_DETAIL SELLER,ADVERT_SELLER_FEEDBACK FEEDBACK,ADVERT_USER_ACCOUNT ACCOUNT,ADVERT_RESORUCE_URL RESOURCE,ADVERT_USER_PROFILE PROFILE
                                              WHERE  SELLER.SELLER_ID=@sellerID AND FEEDBACK.SELLER_ID=SELLER.SELLER_ID AND ACCOUNT.USER_ID=SELLER.USER_ID
                                              AND PROFILE.PROFILE_IMAGE_URL=SELLER.USER_ID AND PROFILE.PROFILE_IMAGE_URL=RESOURCE.URL_ID
                                              GROUP BY SELLER_NAME,SELLER.USER_ID,REGISTERED_DATE,URL_STRING";

        public string Q_GET_RESOURCE_LIST= @"SELECT RESOURCE_NAME,RESOURCE_TYPE_ID,'http://192.168.69.1/AdvertiseService'+PREVIEW.URL_STRING AS PREVIEW_URL,'http://192.168.69.1/AdvertiseService'+RESURL.URL_STRING AS RESOURCE_URL
                                             FROM ADVERT_ADDITIONAL_RESOURCE RESRCE,ADVERT_RESORUCE_URL RESURL,ADVERT_PREVIEW_URL PREVIEW
                                             WHERE  ADVERT_ID=@advertID AND RESRCE.PREVIEW_URL_ID=PREVIEW.URL_ID 
                                             AND RESRCE.URL_ID=RESURL.URL_ID  ORDER BY RESOURCE_TYPE_ID";

        public string Q_GET_USER_REVIEW_LIST = @"SELECT REVIEW.REVIEW_RATING,REVIEW.REVIEW_HEADING,REVIEW.REVIEW_CONTENT,REVIEW.REVIEW_DATE,ACCOUNT.ADVERTISEME_NAME 
                                                FROM ADVERT_USER_REVIEW REVIEW , ADVERT_USER_ACCOUNT ACCOUNT
                                                WHERE REVIEW.USER_ID=ACCOUNT.USER_ID AND ADVERT_ID=@advertID ORDER BY REVIEW.REVIEW_DATE DESC";

        public string Q_GET_SELLER_REVIEW = @"SELECT DISTINCT(SELECT COUNT (USER_ID) FROM ADVERT_SELLER_FEEDBACK 
                                              WHERE SELLER_ID=@sellerID AND REVIEW_FLG=1) AS POSTIVE_COUNT,(SELECT COUNT (USER_ID) FROM ADVERT_SELLER_FEEDBACK 
                                              WHERE SELLER_ID=@sellerID AND REVIEW_FLG=0) AS NEUTRAL_COUNT,(SELECT COUNT (USER_ID) FROM ADVERT_SELLER_FEEDBACK 
                                              WHERE SELLER_ID=@sellerID AND REVIEW_FLG=-1) AS NEGATIVE_COUNT FROM ADVERT_SELLER_FEEDBACK WHERE SELLER_ID=@sellerID";

        public string Q_GET_SELLER_FEEDBACK = @"SELECT ACCOUNT.ADVERTISEME_NAME,REVIEW_FLG,REVIEW_COMMENT,REVIEW_DATE 
                                                FROM ADVERT_SELLER_FEEDBACK FEEDBACK, ADVERT_USER_ACCOUNT ACCOUNT 
                                                WHERE  FEEDBACK.USER_ID=ACCOUNT.USER_ID AND SELLER_ID=@sellerID ORDER BY REVIEW_DATE DESC";


        public string Q_GET_DAILY_DEAL_LIST = @"SELECT ADVERT.ADVERT_ID,ADVERT_NAME,LIST_PRICE,SELL_PRICE,SAVE_PERCENTAGE,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING
                                                FROM ADVERT_ADVERTISEMENT_DETAIL ADVERT, ADVERT_ITEM_PRICE PRICE,ADVERT_PREVIEW_URL URL
                                                WHERE ADVERT.ADVERT_ID=PRICE.ADVERT_ID AND URL.URL_ID='ad'+ADVERT.ADVERT_ID AND  SELLER_OFFER_FLG=1";

        public string Q_GET_ADVERT_LIST_BY_SELLER = @"SELECT DISTINCT ADVERT.ADVERT_ID,ADVERT_TITLE,SELLER_NAME,SELL_PRICE,AVG(REVIEW_RATING) AS ADVERT_RATING,COUNT(REVIEW.ADVERT_ID) AS REVIEW_COUNT,'http://192.168.69.1/AdvertiseService'+URL_STRING AS RESOURCE_URL
                                                    FROM ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_ITEM_PRICE PRICE,ADVERT_USER_REVIEW REVIEW,ADVERT_PREVIEW_URL URL,ADVERT_SELLER_DETAIL SELLER
                                                    WHERE REVIEW.ADVERT_ID= ADVERT.ADVERT_ID AND URL_ID='ad'+REVIEW.ADVERT_ID AND SELLER.SELLER_ID=ADVERT.SELLER_ID AND ADVERT.ADVERT_ID=PRICE.ADVERT_ID AND SELLER.SELLER_ID=@sellerID
                                                    GROUP BY ADVERT.ADVERT_ID,ADVERT_TITLE,URL_STRING,SELL_PRICE,SELLER_NAME";

        public string Q_GET_DAILY_DEAL_ITEM = @"SELECT ADVERT.ADVERT_ID,ADVERT.ADVERT_NAME,PRICE.LIST_PRICE,PRICE.SELL_PRICE,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING FROM ADVERT_DAILY_DEAL DEAL ,ADVERT_ADVERTISEMENT_DETAIL ADVERT, ADVERT_ITEM_PRICE PRICE,ADVERT_PREVIEW_URL URL
                                                WHERE DEAL.ADVERT_ID=ADVERT.ADVERT_ID AND ADVERT.ADVERT_ID=PRICE.ADVERT_ID AND URL.URL_ID='ad'+DEAL.ADVERT_ID
                                                AND  DEAL.DEAL_DATE BETWEEN GETDATE()- 1 AND GETDATE()";

        public string Q_GET_BEST_DEALS_LIST = @"SELECT DEALS.ADVERT_ID,ADVERT.ADVERT_TITLE,DEALS.DEAL_DESCRIPTION,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING 
                                                FROM ADVERT_BEST_DEALS DEALS, ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_PREVIEW_URL URL
                                                WHERE DEALS.ADVERT_ID=ADVERT.ADVERT_ID AND URL.URL_ID='ad'+DEALS.ADVERT_ID";

        public string Q_GET_BEST_DEAL_ADVERT_DETAIL= @" SELECT ADVERT.ADVERT_ID, ADVERT.SELLER_ID, ADVERT_TITLE, ADVERT.USER_ID, PRODUCT_FEATURES, PRODUCT_DESCRIPTION, PRODUCT_DETAIL, ADDITIONAL_INFO, PRODUCT_NOTE, SELLER_OFFER_FLG,  ADVERT_URL, BUYONLINE_FLG, BUYONLINE_URL, 
                                                        LIST_PRICE,SELL_PRICE, SAVE_AMOUNT, STAFF_PICK_FLG, SAVE_PERCENTAGE,SELLER_NAME,'http://192.168.69.1/AdvertiseService'+PREVIEW.URL_STRING,DEALS.DEAL_STATUS,DEALS.DEAL_DESCRIPTION
                                                        FROM ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_ITEM_PRICE PRICE,ADVERT_SELLER_DETAIL SELLER,ADVERT_PREVIEW_URL PREVIEW,ADVERT_BEST_DEALS DEALS
                                                        WHERE ADVERT.ADVERT_ID=@advertID AND SELLER.SELLER_ID=ADVERT.SELLER_ID AND ADVERT.ADVERT_ID=PRICE.ADVERT_ID  AND ADVERT.ADVERT_ID=DEALS.ADVERT_ID
                                                        AND PREVIEW.URL_ID='ad'+@advertID";

        public string Q_GET_USER_RECOMMENDATION_LIST = @"SELECT DISTINCT ADVERT.ADVERT_ID,ADVERT_TITLE,SELLER_NAME,SELL_PRICE,'http://192.168.69.1/AdvertiseService'+URL_STRING AS RESOURCE_URL
                                                         FROM ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_ITEM_PRICE PRICE,ADVERT_PREVIEW_URL URL,ADVERT_SELLER_DETAIL SELLER,
                                                         ADVERT_USER_RECOMMENDATION RECOMND WHERE URL_ID='ad'+ADVERT.ADVERT_ID 
                                                         AND ADVERT.SELLER_ID=SELLER.SELLER_ID AND ADVERT.ADVERT_ID=PRICE.ADVERT_ID
                                                         AND RECOMND.ADVERT_ID=ADVERT.ADVERT_ID AND RECOMND.USER_ID=@userID";

        public string Q_GET_USER_CONNECTION_LIST = @"(
                                                        SELECT CONNECTION_ID  AS CONNECTION_ID,PROF.CITY,PROF.STATE,PROF.COUNTRY,ACNT.ADVERTISEME_NAME,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING FROM ADVERT_USER_CONNECTION CONN,ADVERT_USER_PROFILE PROF,ADVERT_USER_ACCOUNT ACNT,ADVERT_RESORUCE_URL URL
                                                        WHERE CONN.CONNECTION_ID=PROF.USER_ID  AND CONN.CONNECTION_ID=ACNT.USER_ID
                                                        AND  CONN.USER_ID=@userID AND URL.URL_ID=CONN.CONNECTION_ID AND PROF.FULL_NAME LIKE '%"+searchQuery+"%'"+
                                                   @")  UNION
                                                     (
                                                        SELECT CONN.USER_ID AS CONNECTION_ID,PROF.CITY,PROF.STATE,PROF.COUNTRY,ACNT.ADVERTISEME_NAME,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING FROM ADVERT_USER_CONNECTION CONN,ADVERT_USER_PROFILE PROF,ADVERT_USER_ACCOUNT ACNT,ADVERT_RESORUCE_URL URL
                                                        WHERE CONN.USER_ID=PROF.USER_ID  AND  CONN.USER_ID=ACNT.USER_ID
                                                        AND CONN.CONNECTION_ID=@userID AND URL.URL_ID=CONN.USER_ID AND PROF.FULL_NAME LIKE '%"+searchQuery+"%')";

        public string Q_GET_CONNECTION_REQUEST_LIST = @"SELECT REQ.REQUESTER_ID,PROF.CITY,PROF.STATE,PROF.COUNTRY,ACNT.ADVERTISEME_NAME,PROF.FULL_NAME,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING 
                                                        FROM ADVERT_CONTACT_REQUEST REQ,ADVERT_USER_PROFILE PROF,ADVERT_USER_ACCOUNT ACNT,ADVERT_RESORUCE_URL URL
                                                        WHERE REQ.REQUESTER_ID=PROF.USER_ID AND REQ.REQUESTER_ID=ACNT.USER_ID AND URL.URL_ID=REQ.REQUESTER_ID
                                                        AND REQ.USER_ID=@userID";

        public string Q_GET_USER_VIEWS_LIST = @"SELECT VW.ADVERT_ID,ADVERT.ADVERT_TITLE,SELLER.SELLER_NAME,VW.VIEW_DATE,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING
                                                FROM ADVERT_USER_VIEWS VW, ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_SELLER_DETAIL SELLER, ADVERT_PREVIEW_URL URL
                                                WHERE VW.ADVERT_ID=ADVERT.ADVERT_ID AND ADVERT.SELLER_ID=SELLER.SELLER_ID
                                                AND URL.URL_ID='ad'+ADVERT.ADVERT_ID AND VW.USER_ID=@userID
                                                ORDER BY VW.VIEW_DATE DESC";

        public string Q_GET_USER_ACTIVITY_LIST = @"SELECT ACT.*,USR.FULL_NAME, ADVERT.ADVERT_TITLE,PROF.FULL_NAME,SELLER.SELLER_NAME FROM 
                                                   ADVERT_USER_ACTIVITY ACT LEFT JOIN ADVERT_ADVERTISEMENT_DETAIL ADVERT ON ACT.ADVERT_ID=ADVERT.ADVERT_ID
                                                   LEFT JOIN ADVERT_USER_PROFILE PROF ON ACT.CONNECTION_ID=PROF.USER_ID
                                                   LEFT JOIN ADVERT_USER_PROFILE USR ON ACT.USER_ID=USR.USER_ID
                                                   LEFT JOIN ADVERT_SELLER_DETAIL SELLER ON ACT.SELLER_ID=SELLER.SELLER_ID
                                                   WHERE ACT.USER_ID=@userID";

        public string Q_GET_USER_ACCOUNT_COUNT = @"SELECT 
                                                  (SELECT COUNT(ACTIVITY_ID) AS ACTIVITY_COUNT FROM ADVERT_USER_ACTIVITY
                                                   WHERE USER_ID=@userID) AS ACTIVITY_COUNT,
                                                  (SELECT COUNT(VIEW_ID) AS VIEW_COUNT FROM ADVERT_USER_VIEWS
                                                   WHERE USER_ID=@userID) AS VIEW_COUNT,
                                                  (SELECT COUNT(REQUEST_ID) AS REQUEST_COUNT FROM ADVERT_CONTACT_REQUEST
                                                   WHERE  USER_ID=@userID) AS REQUEST_COUNT,
                                                  (SELECT COUNT(CONNECTION_ID) AS CONNECTION_COUNT FROM
                                                 ((SELECT CONNECTION_ID AS CONNECTION_ID FROM ADVERT_USER_CONNECTION
                                                   WHERE USER_ID=@userID) UNION
                                                  (SELECT USER_ID AS CONNECTION_ID FROM ADVERT_USER_CONNECTION
                                                   WHERE CONNECTION_ID=@userID) )AS CONNECTION_COUNT) AS CONNECTION_COUNT
                                                   FROM ADVERT_USER_ACCOUNT WHERE USER_ID=@userID";
        public string Q_GET_MESSAGE_INBOX_LIST = @"SELECT MSG.*,PROF.FULL_NAME,PROF.CITY,PROF.STATE,PROF.COUNTRY,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING FROM ADVERT_MESSAGE MSG, 
                                                   ADVERT_USER_PROFILE PROF,ADVERT_RESORUCE_URL URL 
                                                   WHERE MSG.SENDER_ID=PROF.USER_ID AND URL.URL_ID=MSG.SENDER_ID AND RECIEVER_ID=@userID";

        public string Q_GET_MESSAGE_SENT_LIST = @"SELECT MSG.*,PROF.FULL_NAME,PROF.CITY,PROF.STATE,PROF.COUNTRY,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING FROM ADVERT_MESSAGE MSG, ADVERT_USER_PROFILE PROF,
                                                  ADVERT_RESORUCE_URL URL WHERE MSG.RECIEVER_ID=PROF.USER_ID AND
                                                  URL.URL_ID=MSG.RECIEVER_ID AND SENDER_ID=@userID";

        public string Q_GET_MESSAGE_SAVED_LIST = @"SELECT MSG.*,PROF.FULL_NAME,PROF.CITY,PROF.STATE,PROF.COUNTRY,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING 
                                                   FROM ADVERT_MESSAGE MSG, ADVERT_SAVED_MESSAGE SVMSG,ADVERT_USER_PROFILE PROF,ADVERT_RESORUCE_URL URL 
                                                   WHERE MSG.SENDER_ID=PROF.USER_ID AND SVMSG.USER_ID=MSG.RECIEVER_ID
                                                   AND URL.URL_ID=MSG.SENDER_ID AND SVMSG.USER_ID=@userID";
        
        public string Q_GET_INBOX_MESSAGE_DETAIL = @"SELECT MSG.*,PROF.FULL_NAME,PROF.CITY,PROF.STATE,PROF.COUNTRY,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING FROM ADVERT_MESSAGE MSG, 
                                                   ADVERT_USER_PROFILE PROF,ADVERT_RESORUCE_URL URL 
                                                   WHERE MSG.SENDER_ID=PROF.USER_ID AND URL.URL_ID=MSG.SENDER_ID AND MSG.MESSAGE_ID=@messageID";
     
        public string Q_GET_SENT_MESSAGE_DETAIL = @"SELECT MSG.*,PROF.FULL_NAME,PROF.CITY,PROF.STATE,PROF.COUNTRY,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING FROM ADVERT_MESSAGE MSG, ADVERT_USER_PROFILE PROF,
                                                  ADVERT_RESORUCE_URL URL WHERE MSG.RECIEVER_ID=PROF.USER_ID AND
                                                  URL.URL_ID=MSG.RECIEVER_ID AND MSG.MESSAGE_ID=@messageID";

        public string Q_GET_SAVED_MESSAGE_DETAIL = @"SELECT MSG.*,PROF.FULL_NAME,PROF.CITY,PROF.STATE,PROF.COUNTRY,'http://192.168.69.1/AdvertiseService'+URL.URL_STRING AS URL_STRING 
                                                   FROM ADVERT_MESSAGE MSG, ADVERT_SAVED_MESSAGE SVMSG,ADVERT_USER_PROFILE PROF,ADVERT_RESORUCE_URL URL 
                                                   WHERE MSG.SENDER_ID=PROF.USER_ID AND SVMSG.USER_ID=MSG.RECIEVER_ID
                                                   AND URL.URL_ID=MSG.SENDER_ID AND MSG.MESSAGE_ID=@messageID";
        public string Q_GET_ADVERT_LIST_BY_USER_REFERENCE = @"SELECT DISTINCT ADVERT.ADVERT_ID,ADVERT_TITLE,SELLER_NAME,SELL_PRICE,AVG(REVIEW_RATING) AS ADVERT_RATING,COUNT(REVIEW.ADVERT_ID) AS REVIEW_COUNT,'http://192.168.69.1/AdvertiseService'+URL_STRING AS RESOURCE_URL
                                            FROM ADVERT_ADVERTISEMENT_DETAIL ADVERT,ADVERT_ITEM_PRICE PRICE,ADVERT_USER_REVIEW REVIEW,ADVERT_PREVIEW_URL URL,ADVERT_SELLER_DETAIL SELLER
                                            WHERE REVIEW.ADVERT_ID= ADVERT.ADVERT_ID AND URL_ID='ad'+REVIEW.ADVERT_ID AND SELLER.SELLER_ID=ADVERT.SELLER_ID AND ADVERT.ADVERT_ID=PRICE.ADVERT_ID
                                            AND ADVERT.ADVERT_ID IN (@qString)
                                            GROUP BY ADVERT.ADVERT_ID,ADVERT_TITLE,URL_STRING,SELL_PRICE,SELLER_NAME";
    }
}
